### PR TITLE
Fix self.detect_facter

### LINKED ISSUE #99: self.detect_facter is not working correctly
Plus, there are currently 2 instances of the method.

### PR DESCRIPTION
**Pull request by untergeek**
There were two instances of this method, the second empty.

The first was calling in an apparently older format.  The newer calls should be symbols:

```
jruby-1.7.25 :005 > Facter.list
 => [:kernel, :domain, :network_docker0, :network_eth0, :network_lo, :network_veth9c88ef2, 
:puppetversion, :blockdevice_sda_size, :blockdevice_sda_vendor, :blockdevice_sda_model, 
:blockdevice_sdb_size, :blockdevice_sdb_vendor, :blockdevice_sdb_model, :blockdevices, :id, 
:hardwaremodel, :ipaddress6, :lsbmajdistrelease, :lsbdistdescription, :iphostnumber, :partitions, 
:processors, :architecture, :operatingsystem, :os, :processor0, :processor1, :processor2, :processor3, 
:processor4, :processor5, :processor6, :processor7, :processorcount, :processor, :uptime_seconds, 
:virtual, :is_virtual, :zonename, :ps, :fqdn, :osfamily, :gid, :kernelversion, :operatingsystemmajrelease, 
:uniqueid, :operatingsystemrelease, :lsbdistid, :system_uptime, :netmask, :ec2_metadata, :ec2_userdata, 
:kernelmajversion, :kernelrelease, :is_rsc, :rsc_region, :rsc_instance_id, :hardwareisa, :sshdsakey, 
:sshfp_dsa, :sshrsakey, :sshfp_rsa, :sshecdsakey, :sshfp_ecdsa, :sshed25519key, :sshfp_ed25519, 
:dhcp_servers, :zfs_version, :uptime_days, :rubyversion, :selinux, :selinux_enforced, 
:selinux_policyversion, :selinux_current_mode, :selinux_config_mode, :selinux_config_policy, :gce, 
:ipaddress, :lsbdistrelease, :rubysitedir, :memorysize, :memoryfree, :swapsize, :swapfree, :swapsize_mb, 
:swapfree_mb, :memorysize_mb, :memoryfree_mb, :swapencrypted, :cfkey, :lsbminordistrelease, 
:augeasversion, :lsbrelease, :hostname, :zpool_version, :rubyplatform, :lsbdistcodename, :interfaces, 
:ipaddress_docker0, :ipaddress6_docker0, :macaddress_docker0, :netmask_docker0, :mtu_docker0, 
:ipaddress_eth0, :ipaddress6_eth0, :macaddress_eth0, :netmask_eth0, :mtu_eth0, :ipaddress_lo, 
:ipaddress6_lo, :macaddress_lo, :netmask_lo, :mtu_lo, :ipaddress_veth9c88ef2, 
:ipaddress6_veth9c88ef2, :macaddress_veth9c88ef2, :netmask_veth9c88ef2, :mtu_veth9c88ef2, :vlans, 
:uptime_hours, :timezone, :macaddress, :facterversion, :uptime, :filesystems, :xendomains, 
:physicalprocessorcount, :path, :system32]
```

fixes #99

### CODE REVIEW

File: lib/pleaserun/detector.rb [hunk 1]
```diff
@@ -79,8 +79,8 @@ def self.detect_ohai
   def self.detect_facter
     require "facter"
 
-    platform = Facter.fact["operatingsystem"]
-    version = Facter.fact["operatingsystemrelease"]
+    platform = Facter.value(:operatingsystem)
```
Comment (jordansissel) [inline lib/pleaserun/detector.rb]: hmm, this may break compatibility with older facter versions, but I'm ok wiating until someone needs older support. +1 on this change
